---
title: "Marking Scans Project"
author: "Andrew Maloney"
date: "9/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eval=FALSE, include=FALSE}

library(tidyverse)
library(x3ptools)
library(bulletxtrctr)
library(ggplot2)
library(keras)
library(purrr)
library(svMisc)

```



```{r eval=FALSE, include=FALSE}

data_dir <- "/media/Raven/Masks/Completed/LAPD"


df <- tibble(path = list.files(path = file.path(data_dir, "Megan"), 
                               pattern = ".x3p", recursive = T, 
                               full.names = T)) %>% mutate(x3p = map(path, read_x3p))



```

```{r eval=FALSE, include=FALSE}

df_1 <- df[1:100, ]
df_2 <- df[101:200,]
df_3 <- df[201:300,]
df_4 <- df[301:400,]
df_5 <- df[401:448,]
```

```{r eval=FALSE, warning=FALSE, include=FALSE}
f = function(x, n){
    x - 128*(1:n)
  
}


for(i in 1:nrow(df_1)){
  
  progress(i, progress.bar = TRUE)
  Sys.sleep(0.01)
  dimension_x <- dim(df_1$x3p[[i]]$surface.matrix)[1]
  dimension_y <- dim(df_1$x3p[[i]]$surface.matrix)[2]
  
  division_x <- dim(df_1$x3p[[i]]$surface.matrix)[1] / 128
  division_y <- dim(df_1$x3p[[i]]$surface.matrix)[2] / 128
  
  grid_lengths_x <- c(f(dimension_x, division_x), 0)
  grid_lengths_y <- c(f(dimension_y, division_y), 0)
  
  grid_outline <- expand.grid(grid_lengths_x, grid_lengths_y)
  
  grid_outline <- grid_outline %>% filter(Var1 >= 0 & Var2 >= 0)
  
  df_1$chop_storage[[i]] <- map2(.x = grid_outline$Var1 ,
                               .y = grid_outline$Var2 ,
                               .f = x3p_crop, x3p = df_1$x3p[[i]],
                               width = 128,
                               height = 128)
  
}



saveRDS(df_1, file="LAPD_Chopped_data_1.Rda")


```

```{r eval=FALSE, warning=FALSE, include=FALSE}




for(i in 1:nrow(df_2)){
  
  progress(i, progress.bar = TRUE)
  Sys.sleep(0.01)
  dimension_x <- dim(df_2$x3p[[i]]$surface.matrix)[1]
  dimension_y <- dim(df_2$x3p[[i]]$surface.matrix)[2]
  
  division_x <- dim(df_2$x3p[[i]]$surface.matrix)[1] / 128
  division_y <- dim(df_2$x3p[[i]]$surface.matrix)[2] / 128
  
  grid_lengths_x <- c(f(dimension_x, division_x), 0)
  grid_lengths_y <- c(f(dimension_y, division_y), 0)
  
  grid_outline <- expand.grid(grid_lengths_x, grid_lengths_y)
  
  grid_outline <- grid_outline %>% filter(Var1 >= 0 & Var2 >= 0)
  
  df_2$chop_storage[[i]] <- map2(.x = grid_outline$Var1 ,
                               .y = grid_outline$Var2 ,
                               .f = x3p_crop, x3p = df_2$x3p[[i]],
                               width = 128,
                               height = 128)
  
}

saveRDS(df_2, file="LAPD_Chopped_data_2.Rda")

```

```{r eval=FALSE, warning=FALSE, include=FALSE}

for(i in 1:nrow(df_3)){
  
  progress(i, progress.bar = TRUE)
  Sys.sleep(0.01)
  dimension_x <- dim(df_3$x3p[[i]]$surface.matrix)[1]
  dimension_y <- dim(df_3$x3p[[i]]$surface.matrix)[2]
  
  division_x <- dim(df_3$x3p[[i]]$surface.matrix)[1] / 128
  division_y <- dim(df_3$x3p[[i]]$surface.matrix)[2] / 128
  
  grid_lengths_x <- c(f(dimension_x, division_x), 0)
  grid_lengths_y <- c(f(dimension_y, division_y), 0)
  
  grid_outline <- expand.grid(grid_lengths_x, grid_lengths_y)
  
  grid_outline <- grid_outline %>% filter(Var1 >= 0 & Var2 >= 0)
  
  df_3$chop_storage[[i]] <- map2(.x = grid_outline$Var1 ,
                               .y = grid_outline$Var2 ,
                               .f = x3p_crop, x3p = df_3$x3p[[i]],
                               width = 128,
                               height = 128)
  
}


saveRDS(df_3, file="LAPD_Chopped_data_3.Rda")


```

```{r eval=FALSE, warning=FALSE, include=FALSE}




for(i in 1:nrow(df_4)){
  
  progress(i, progress.bar = TRUE)
  Sys.sleep(0.01)
  dimension_x <- dim(df_4$x3p[[i]]$surface.matrix)[1]
  dimension_y <- dim(df_4$x3p[[i]]$surface.matrix)[2]
  
  division_x <- dim(df_4$x3p[[i]]$surface.matrix)[1] / 128
  division_y <- dim(df_4$x3p[[i]]$surface.matrix)[2] / 128
  
  grid_lengths_x <- c(f(dimension_x, division_x), 0)
  grid_lengths_y <- c(f(dimension_y, division_y), 0)
  
  grid_outline <- expand.grid(grid_lengths_x, grid_lengths_y)
  
  grid_outline <- grid_outline %>% filter(Var1 >= 0 & Var2 >= 0)
  
  df_4$chop_storage[[i]] <- map2(.x = grid_outline$Var1 ,
                               .y = grid_outline$Var2 ,
                               .f = x3p_crop, x3p = df_4$x3p[[i]],
                               width = 128,
                               height = 128)
  
}


saveRDS(df_4, file="LAPD_Chopped_data_4.Rda")

```

```{r eval=FALSE, warning=FALSE, include=FALSE}


for(i in 1:nrow(df_5)){
  
  progress(i, progress.bar = TRUE)
  Sys.sleep(0.01)
  dimension_x <- dim(df_5$x3p[[i]]$surface.matrix)[1]
  dimension_y <- dim(df_5$x3p[[i]]$surface.matrix)[2]
  
  division_x <- dim(df_5$x3p[[i]]$surface.matrix)[1] / 128
  division_y <- dim(df_5$x3p[[i]]$surface.matrix)[2] / 128
  
  grid_lengths_x <- c(f(dimension_x, division_x), 0)
  grid_lengths_y <- c(f(dimension_y, division_y), 0)
  
  grid_outline <- expand.grid(grid_lengths_x, grid_lengths_y)
  
  grid_outline <- grid_outline %>% filter(Var1 >= 0 & Var2 >= 0)
  
  df_5$chop_storage[[i]] <- map2(.x = grid_outline$Var1 ,
                               .y = grid_outline$Var2 ,
                               .f = x3p_crop, x3p = df_5$x3p[[i]],
                               width = 128,
                               height = 128)
  
}


saveRDS(df_5, file="LAPD_Chopped_data_5.Rda")

```

```{r eval=FALSE, include=FALSE}

df_1 <- readRDS("LAPD_Chopped_data_1.Rda")
df_2 <- readRDS("LAPD_Chopped_data_2.Rda")
df_3 <- readRDS("LAPD_Chopped_data_3.Rda")
df_4 <- readRDS("LAPD_Chopped_data_4.Rda")
df_5 <- readRDS("LAPD_Chopped_data_5.Rda")


```


```{r eval=FALSE, include=FALSE}


x3p_df_ex <- x3p_to_df(df_1$chop_storage[[1]][[1]])


x3p_look <- df_1$chop_storage[[1]][[1]]


df_1$chop_storage[[1]][[1]]$mask
```


```{r eval=FALSE, include=FALSE}

scan_vector_1 <- as.vector(t(df_1$chop_storage[[1]][[1]]$surface.matrix))
scan_vector_2 <- as.vector(t(df_1$chop_storage[[1]][[2]]$surface.matrix))



```

```{r eval=FALSE, include=FALSE}

df_sub <- df_1[1:5, ]

df_1 <- unnest(df_1, chop_storage)

```

```{r eval=FALSE, include=FALSE}

storage_df <- tibble()

for (i in 1:nrow(df_sub)){
  
  
  df_sub$dataframes[[i]] <- data.frame(x3p_to_df(df_sub$chop_storage[[i]]))
  
  
}


#test <- map(.x = df_sub$chop_storage, .f = x3p_to_df)


test_1 <- x3p_to_df(df_1$chop_storage[[1]])
test_2 <- x3p_to_df(df_1$chop_storage[[2000]])
test_3 <- x3p_to_df(df_1$chop_storage[[10000]])
test_4 <- x3p_to_df(df_1$chop_storage[[15000]])
test_5 <- x3p_to_df(df_1$chop_storage[[20000]])



array_test_1 <- array(c(test_1$x, test_1$y, test_1$value),
                      dim = c(128, 128, 1, 1))


array_test_2 <- array(c(test_2$x, test_2$y, test_2$value),
                      dim = c(16384, 3, 1, 1))

array_test_3 <- array(c(test_3$x, test_3$y, test_3$value),
                      dim = c(16384, 3, 1, 1))

array_test_4 <- array(c(test_4$x, test_4$y, test_4$value),
                      dim = c(16384, 3, 1, 1))

array_test_5 <- array(c(test_5$x, test_5$y, test_5$value),
                      dim = c(16384, 3, 1, 1))


#test_1$annotation <- as.character(test_1$annotation)
#test_1$annotation[test_1$annotation == "right groove"] <- 0
#test_1$annotation[test_1$annotation == "well expressed striae"] <- 1
#test_1$annotation[test_1$annotation == "no striations"] <- 2
#test_1$annotation[test_1$annotation == "left groove"] <- 3

#test_2$annotation <- as.character(test_2$annotation)
#test_2$annotation[test_2$annotation == "right groove"] <- 0
#test_2$annotation[test_2$annotation == "well expressed striae"] <- 1
#test_2$annotation[test_2$annotation == "no striations"] <- 2
#test_2$annotation[test_2$annotation == "left groove"] <- 3

#test_3$annotation <- as.character(test_3$annotation)
#test_3$annotation[test_3$annotation == "right groove"] <- 0
#test_3$annotation[test_3$annotation == "well expressed striae"] <- 1
#test_3$annotation[test_3$annotation == "no striations"] <- 2#
#test_3$annotation[test_3$annotation == "left groove"] <- 3

#test_4$annotation <- as.character(test_4$annotation)
#test_4$annotation[test_4$annotation == "right groove"] <- 0
#test_4$annotation[test_4$annotation == "well expressed striae"] <- 1
#test_4$annotation[test_4$annotation == "no striations"] <- 2
#test_4$annotation[test_4$annotation == "left groove"] <- 3

#test_5$annotation <- as.character(test_5$annotation)
#test_5$annotation[test_5$annotation == "right groove"] <- 0
#test_5$annotation[test_5$annotation == "well expressed striae"] <- 1
#test_5$annotation[test_5$annotation == "no striations"] <- 2
#test_5$annotation[test_5$annotation == "left groove"] <- 3


#array_test_1y <- array(c(test_1$annotation),
                     #dim = c(16384, 1))
#array_test_2y <- array(c(test_2$annotation),
                      #dim = c(16384, 1))
#array_test_3y <- array(c(test_3$annotation),
                      #dim = c(16384, 1))
#array_test_4y <- array(c(test_4$annotation),
                      #dim = c(16384, 1))
#array_test_5y <- array(c(test_5$annotation),
                      #dim = c(16384, 1))

#dim(train_preds)

#array_test_1y

array_test_1[1, , , ,]
```


```{r eval=FALSE, include=FALSE}

library(abind)

train_explanatory <- abind(array_test_1,array_test_2, array_test_3, array_test_4, array_test_5, along=0)

train_preds <- rbind(test_1, test_2, test_3, test_4, test_5)


#train_preds <- abind(array_test_1y, array_test_2y, array_test_3y, array_test_4y, array_test_5y, along = 0)


dim(train_explanatory)
dim(train_preds)

```


```{r eval=FALSE, include=FALSE}



class(train_preds$annotation)

train_preds$annotation <- as.character(train_preds$annotation)
train_preds$annotation[train_preds$annotation == "right groove"] <- 0
train_preds$annotation[train_preds$annotation == "well expressed striae"] <- 1
train_preds$annotation[train_preds$annotation == "no striations"] <- 2
train_preds$annotation[train_preds$annotation == "left groove"] <- 3

train_preds$annotation <- as.numeric(train_preds$annotation)


```


```{r eval=FALSE, include=FALSE}

model <- keras_model_sequential() %>%
  layer_conv_3d(filters = 32, kernel_size = c(3, 3, 3), padding = 'same', activation = "relu", input_shape = c(16384, 3, 1, 1), data_format = "channels_last") %>%
  layer_max_pooling_3d(pool_size = c(1, 1, 1)) %>%
  #layer_conv_3d(filters = 64, kernel_size = c(3, 3, 3), activation = "relu") %>%
  #layer_max_pooling_3d(pool_size = c(2, 2, 2)) %>%
  layer_flatten() %>%
  layer_dense(units = 256, activation = "relu") %>%
  layer_dense(units = 4, activation = "softmax")



```

```{r}


model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)

model %>% fit(
  train_explanatory, train_preds$annotation, epochs = 5,
)
```






