---
title: "Hopefully"
author: "Andrew Maloney"
date: "11/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

library(tidyverse)
library(x3ptools)
library(ggplot2)
library(keras)
library(purrr)
library(reshape2)
library(plotly)
library(abind)
library(tensorflow)

#install_keras(tensorflow = "gpu")

```

```{r}



df_1 <- readRDS("LAPD_Chopped_data_1.Rda")

df_1 <- df_1 %>% select(-chop_storage)


```


```{r}
#Take first 100 x3p files
df_2 <- df_1

head(df_1)
```

```{r}

#Extract the min x3p and max x3p surface matrix values for rescaling purposes if needed

for(i in 1:nrow(df_1)){
  
  df_1$x3pmin[[i]] <- min(df_1$x3p[[i]]$surface.matrix, na.rm = TRUE)
  df_1$x3pmax[[i]] <- max(df_1$x3p[[i]]$surface.matrix, na.rm = TRUE)
  
}


```

```{r}

for(i in 1:nrow(df_2)){
  
  df_2$x3pmin[[i]] <- min(df_2$x3p[[i]]$surface.matrix, na.rm = TRUE)
  df_2$x3pmax[[i]] <- max(df_2$x3p[[i]]$surface.matrix, na.rm = TRUE)
  
}

```

```{r}
f = function(x, n){
    x - 128*(1:n)
  
}


for(i in 1:nrow(df_1)){
  
  
  dimension_x <- dim(df_1$x3p[[i]]$surface.matrix)[1]
  dimension_y <- dim(df_1$x3p[[i]]$surface.matrix)[2]
  
  division_x <- dim(df_1$x3p[[i]]$surface.matrix)[1] / 128
  division_y <- dim(df_1$x3p[[i]]$surface.matrix)[2] / 128
  
  grid_lengths_x <- c(f(dimension_x, division_x), 0)
  grid_lengths_y <- c(f(dimension_y, division_y), 0) 
  
  grid_outline <- expand.grid(grid_lengths_x, grid_lengths_y)
  
  grid_outline <- grid_outline %>% filter(Var1 >= 0 & Var2 >= 0)
  
  df_1$chop_storage[[i]] <- map2(.x = grid_outline$Var1 ,
                               .y = grid_outline$Var2 ,
                               .f = x3p_crop, x3p = df_1$x3p[[i]],
                               width = 128,
                               height = 128)
  
}

```

```{r}
#

f = function(x, n){
    x - 256*(1:n)
  
}


for(i in 1:nrow(df_2)){
  
  
  dimension_x <- dim(df_2$x3p[[i]]$surface.matrix)[1]
  dimension_y <- dim(df_2$x3p[[i]]$surface.matrix)[2]
  
  division_x <- dim(df_2$x3p[[i]]$surface.matrix)[1] / 256
  division_y <- dim(df_2$x3p[[i]]$surface.matrix)[2] / 256
  
  grid_lengths_x <- c(f(dimension_x, division_x), 0)
  grid_lengths_y <- c(f(dimension_y, division_y), 0) 
  
  grid_outline <- expand.grid(grid_lengths_x, grid_lengths_y)
  
  grid_outline <- grid_outline %>% filter(Var1 >= 0 & Var2 >= 0)
  
  df_2$chop_storage[[i]] <- map2(.x = grid_outline$Var1 ,
                               .y = grid_outline$Var2 ,
                               .f = x3p_crop, x3p = df_2$x3p[[i]],
                               width = 256,
                               height = 256)
  
}


head(df_1)
head(df_2)
```

```{r}

df_1_0 <- df_1[1:20,]
df_1_1 <- df_1[21:40,]
df_1_2 <- df_1[41:60,]
df_1_3 <- df_1[61:80,]
df_1_4 <- df_1[81:100,]

```

```{r}

df_2_0 <- df_2[1:20,]
df_2_1 <- df_2[21:40,]
df_2_2 <- df_2[41:60,]
df_2_3 <- df_2[61:80,]
df_2_4 <- df_2[81:100,]

```

````{r}



df_1_0 <- unnest(df_1_0, chop_storage)
for(i in 1:nrow(df_1_0)){
  
  df_1_0$labels[[i]] <- unique(pluck(df_1_0$chop_storage[[i]], 6)) 
  
}

df_1_1 <- unnest(df_1_1, chop_storage)
for(i in 1:nrow(df_1_1)){
  
  df_1_1$labels[[i]] <- unique(pluck(df_1_1$chop_storage[[i]], 6)) 
  
}

df_1_2 <- unnest(df_1_2, chop_storage)
for(i in 1:nrow(df_1_2)){
  
  df_1_2$labels[[i]] <- unique(pluck(df_1_2$chop_storage[[i]], 6)) 
  
}

df_1_3 <- unnest(df_1_3, chop_storage)
for(i in 1:nrow(df_1_3)){
  
  df_1_3$labels[[i]] <- unique(pluck(df_1_3$chop_storage[[i]], 6)) 
  
}

df_1_4 <- unnest(df_1_4, chop_storage)
for(i in 1:nrow(df_1_4)){
  
  df_1_4$labels[[i]] <- unique(pluck(df_1_4$chop_storage[[i]], 6)) 
  
}


```

```{r}


df_2_0 <- unnest(df_2_0, chop_storage)
for(i in 1:nrow(df_2_0)){
  
  df_2_0$labels[[i]] <- unique(pluck(df_2_0$chop_storage[[i]], 6)) 
  
}

df_2_1 <- unnest(df_2_1, chop_storage)
for(i in 1:nrow(df_2_1)){
  
  df_2_1$labels[[i]] <- unique(pluck(df_2_1$chop_storage[[i]], 6)) 
  
}

df_2_2 <- unnest(df_2_2, chop_storage)
for(i in 1:nrow(df_2_2)){
  
  df_2_2$labels[[i]] <- unique(pluck(df_2_2$chop_storage[[i]], 6)) 
  
}

df_2_3 <- unnest(df_2_3, chop_storage)
for(i in 1:nrow(df_2_3)){
  
  df_2_3$labels[[i]] <- unique(pluck(df_2_3$chop_storage[[i]], 6)) 
  
}

df_2_4 <- unnest(df_2_4, chop_storage)
for(i in 1:nrow(df_2_4)){
  
  df_2_4$labels[[i]] <- unique(pluck(df_2_4$chop_storage[[i]], 6)) 
  
}



#head(df_2_4)

```

```{r}

df_1_0 <- df_1_0 %>% unnest(c(labels))

array_1_0 = list()
for(i in 1:nrow(df_1_0)){
  
  array_1_0[[i]] <- array(c(df_1_0$chop_storage[[i]]$surface.matrix),
                     dim = c(128, 128, 1, 1))
  
}
array_1_0 <- do.call(abind, c(array_1_0, along = 0))



df_1_0$labels[df_1_0$labels == "#CD7F32FF"] <- 0
df_1_0$labels[df_1_0$labels == "#00FF00FF"] <- 1
df_1_0$labels[df_1_0$labels == "#FFFF66FF"] <- 2
df_1_0$labels[df_1_0$labels == "#66FFFFFF"] <- 3
df_1_0$labels[df_1_0$labels == "#FFFFFFFF"] <- 4
df_1_0$labels[df_1_0$labels == "#1F376CFF"] <- 1
df_1_0$labels[df_1_0$labels == "#FF0080FF"] <- 5

y_1_0 <- as.numeric(df_1_0$labels)

y_1_0 <- to_categorical(y_1_0)

save(array_1_0, y_1_0, file = "train_1_0.RData")

rm(array_1_0, y_1_0, df_1_0)


#________________



df_1_1 <- df_1_1 %>% unnest(c(labels))

array_1_1 = list()
for(i in 1:nrow(df_1_1)){
  
  array_1_1[[i]] <- array(c(df_1_1$chop_storage[[i]]$surface.matrix),
                     dim = c(128, 128, 1, 1))
  
}
array_1_1 <- do.call(abind, c(array_1_1, along = 0))



df_1_1$labels[df_1_1$labels == "#CD7F32FF"] <- 0
df_1_1$labels[df_1_1$labels == "#00FF00FF"] <- 1
df_1_1$labels[df_1_1$labels == "#FFFF66FF"] <- 2
df_1_1$labels[df_1_1$labels == "#66FFFFFF"] <- 3
df_1_1$labels[df_1_1$labels == "#FFFFFFFF"] <- 4
df_1_1$labels[df_1_1$labels == "#1F376CFF"] <- 1
df_1_1$labels[df_1_1$labels == "#FF0080FF"] <- 5

y_1_1 <- as.numeric(df_1_1$labels)

y_1_1 <- to_categorical(y_1_1)

save(array_1_1, y_1_1, file = "train_1_1.RData")

rm(array_1_1, y_1_1, df_1_1)


#-------------------------------------------------------

df_1_2 <- df_1_2 %>% unnest(c(labels))

array_1_2 = list()
for(i in 1:nrow(df_1_2)){
  
  array_1_2[[i]] <- array(c(df_1_2$chop_storage[[i]]$surface.matrix),
                     dim = c(128, 128, 1, 1))
  
}
array_1_2 <- do.call(abind, c(array_1_2, along = 0))



df_1_2$labels[df_1_2$labels == "#CD7F32FF"] <- 0
df_1_2$labels[df_1_2$labels == "#00FF00FF"] <- 1
df_1_2$labels[df_1_2$labels == "#FFFF66FF"] <- 2
df_1_2$labels[df_1_2$labels == "#66FFFFFF"] <- 3
df_1_2$labels[df_1_2$labels == "#FFFFFFFF"] <- 4
df_1_2$labels[df_1_2$labels == "#1F376CFF"] <- 1
df_1_2$labels[df_1_2$labels == "#FF0080FF"] <- 5

y_1_2 <- as.numeric(df_1_2$labels)

y_1_2 <- to_categorical(y_1_2)

save(array_1_2, y_1_2, file = "train_1_2.RData")

rm(array_1_2, y_1_2, df_1_2)


#-----------------------------------------------


df_1_3 <- df_1_3 %>% unnest(c(labels))

array_1_3 = list()
for(i in 1:nrow(df_1_3)){
  
  array_1_3[[i]] <- array(c(df_1_3$chop_storage[[i]]$surface.matrix),
                     dim = c(128, 128, 1, 1))
  
}
array_1_3 <- do.call(abind, c(array_1_3, along = 0))



df_1_3$labels[df_1_3$labels == "#CD7F32FF"] <- 0
df_1_3$labels[df_1_3$labels == "#00FF00FF"] <- 1
df_1_3$labels[df_1_3$labels == "#FFFF66FF"] <- 2
df_1_3$labels[df_1_3$labels == "#66FFFFFF"] <- 3
df_1_3$labels[df_1_3$labels == "#FFFFFFFF"] <- 4
df_1_3$labels[df_1_3$labels == "#1F376CFF"] <- 1
df_1_3$labels[df_1_3$labels == "#FF0080FF"] <- 5

y_1_3 <- as.numeric(df_1_3$labels)

y_1_3 <- to_categorical(y_1_3)

save(array_1_3, y_1_3, file = "train_1_3.RData")

rm(array_1_3, y_1_3, df_1_3)

#----------------------------

df_1_4 <- df_1_4 %>% unnest(c(labels))

array_1_4 = list()
for(i in 1:nrow(df_1_4)){
  
  array_1_4[[i]] <- array(c(df_1_4$chop_storage[[i]]$surface.matrix),
                     dim = c(128, 128, 1, 1))
  
}
array_1_4 <- do.call(abind, c(array_1_4, along = 0))



df_1_4$labels[df_1_4$labels == "#CD7F32FF"] <- 0
df_1_4$labels[df_1_4$labels == "#00FF00FF"] <- 1
df_1_4$labels[df_1_4$labels == "#FFFF66FF"] <- 2
df_1_4$labels[df_1_4$labels == "#66FFFFFF"] <- 3
df_1_4$labels[df_1_4$labels == "#FFFFFFFF"] <- 4
df_1_4$labels[df_1_4$labels == "#1F376CFF"] <- 1
df_1_4$labels[df_1_4$labels == "#FF0080FF"] <- 5

y_1_4 <- as.numeric(df_1_4$labels)

y_1_4 <- to_categorical(y_1_4)

save(array_1_4, y_1_4, file = "train_1_4.RData")

rm(array_1_4, y_1_4, df_1_4)



```

```{r}

df_2_0 <- df_2_0 %>% unnest(c(labels))

array_2_0 = list()
for(i in 1:nrow(df_2_0)){
  
  array_2_0[[i]] <- array(c(df_2_0$chop_storage[[i]]$surface.matrix),
                     dim = c(256, 256, 1, 1))
  
}
array_2_0 <- do.call(abind, c(array_2_0, along = 0))



df_2_0$labels[df_2_0$labels == "#CD7F32FF"] <- 0
df_2_0$labels[df_2_0$labels == "#00FF00FF"] <- 1
df_2_0$labels[df_2_0$labels == "#FFFF66FF"] <- 2
df_2_0$labels[df_2_0$labels == "#66FFFFFF"] <- 3
df_2_0$labels[df_2_0$labels == "#FFFFFFFF"] <- 4
df_2_0$labels[df_2_0$labels == "#1F376CFF"] <- 1
df_2_0$labels[df_2_0$labels == "#FF0080FF"] <- 5

y_2_0 <- as.numeric(df_2_0$labels)

y_2_0 <- to_categorical(y_2_0)

save(array_2_0, y_2_0, file = "train_2_0.RData")


rm(array_2_0, y_2_0, df_2_0)





df_2_1 <- df_2_1 %>% unnest(c(labels))



array_2_1 = list()
for(i in 1:nrow(df_2_1)){
  
  array_2_1[[i]] <- array(c(df_2_1$chop_storage[[i]]$surface.matrix),
                     dim = c(256, 256, 1, 1))
  
}
array_2_1 <- do.call(abind, c(array_2_1, along = 0))



df_2_1$labels[df_2_1$labels == "#CD7F32FF"] <- 0
df_2_1$labels[df_2_1$labels == "#00FF00FF"] <- 1
df_2_1$labels[df_2_1$labels == "#FFFF66FF"] <- 2
df_2_1$labels[df_2_1$labels == "#66FFFFFF"] <- 3
df_2_1$labels[df_2_1$labels == "#FFFFFFFF"] <- 4
df_2_1$labels[df_2_1$labels == "#1F376CFF"] <- 1
df_2_1$labels[df_2_1$labels == "#FF0080FF"] <- 5

y_2_1 <- as.numeric(df_2_1$labels)

y_2_1 <- to_categorical(y_2_1)


save(array_2_1, y_2_1, file = "train_2_1.RData")
rm(array_2_1, y_2_1, df_2_1)



df_2_2 <- df_2_2 %>% unnest(c(labels))


array_2_2 = list()
for(i in 1:nrow(df_2_2)){
  
  array_2_2[[i]] <- array(c(df_2_2$chop_storage[[i]]$surface.matrix),
                     dim = c(256, 256, 1, 1))
  
}
array_2_2 <- do.call(abind, c(array_2_2, along = 0))



df_2_2$labels[df_2_2$labels == "#CD7F32FF"] <- 0
df_2_2$labels[df_2_2$labels == "#00FF00FF"] <- 1
df_2_2$labels[df_2_2$labels == "#FFFF66FF"] <- 2
df_2_2$labels[df_2_2$labels == "#66FFFFFF"] <- 3
df_2_2$labels[df_2_2$labels == "#FFFFFFFF"] <- 4
df_2_2$labels[df_2_2$labels == "#1F376CFF"] <- 1
df_2_2$labels[df_2_2$labels == "#FF0080FF"] <- 5



y_2_2 <- as.numeric(df_2_2$labels)

y_2_2 <- to_categorical(y_2_2)

save(array_2_2, y_2_2, file = "train_2_2.RData")

rm(array_2_2, y_2_2, df_2_2)






df_2_3 <- df_2_3 %>% unnest(c(labels))


array_2_3 = list()
for(i in 1:nrow(df_2_3)){
  
  array_2_3[[i]] <- array(c(df_2_3$chop_storage[[i]]$surface.matrix),
                     dim = c(256, 256, 1, 1))
  
}


array_2_3 <- do.call(abind, c(array_2_3, along = 0))



df_2_3$labels[df_2_3$labels == "#CD7F32FF"] <- 0
df_2_3$labels[df_2_3$labels == "#00FF00FF"] <- 1
df_2_3$labels[df_2_3$labels == "#FFFF66FF"] <- 2
df_2_3$labels[df_2_3$labels == "#66FFFFFF"] <- 3
df_2_3$labels[df_2_3$labels == "#FFFFFFFF"] <- 4
df_2_3$labels[df_2_3$labels == "#1F376CFF"] <- 1
df_2_3$labels[df_2_3$labels == "#FF0080FF"] <- 5



y_2_3 <- as.numeric(df_2_3$labels)

y_2_3 <- to_categorical(y_2_3)

save(array_2_3, y_2_3, file = "train_2_3.RData")

rm(array_2_3, y_2_3, df_2_3)





df_2_4 <- df_2_4 %>% unnest(c(labels))

array_2_4 = list()
for(i in 1:nrow(df_2_4)){
  
  array_2_4[[i]] <- array(c(df_2_4$chop_storage[[i]]$surface.matrix),
                     dim = c(256, 256, 1, 1))
  
}
array_2_4 <- do.call(abind, c(array_2_4, along = 0))



df_2_4$labels[df_2_4$labels == "#CD7F32FF"] <- 0
df_2_4$labels[df_2_4$labels == "#00FF00FF"] <- 1
df_2_4$labels[df_2_4$labels == "#FFFF66FF"] <- 2
df_2_4$labels[df_2_4$labels == "#66FFFFFF"] <- 3
df_2_4$labels[df_2_4$labels == "#FFFFFFFF"] <- 4
df_2_4$labels[df_2_4$labels == "#1F376CFF"] <- 1
df_2_4$labels[df_2_4$labels == "#FF0080FF"] <- 5


y_2_4 <- as.numeric(df_2_4$labels)

y_2_4 <- to_categorical(y_2_4)

save(array_2_4, y_2_4, file = "train_2_4.RData")

rm(array_2_4, y_2_4, df_2_4)

```


